name: mirrorchyan_upload

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  mirrorchyan_full:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get Version Name
        id: version_name
        run: |
          zip -r mirrorchyan.zip `ls`

          version=$(md5sum models_data.json | awk '{ print $1 }')

          echo "version=$version" | tee -a "$GITHUB_OUTPUT"
          # echo "release_note=$release_note" | tee -a "$GITHUB_OUTPUT"

      # - name: Upload Release Note
      #   uses: MirrorChyan/release-note-action@v1
      #   with:
      #     mirrorchyan_rid: ArkModelsRepo

      #     version_name: ${{ steps.version_name.outputs.version }}
      #     release_note: ${{ steps.version_name.outputs.release_note }}

      #     upload_token: ${{ secrets.MIRROR_CHYAN_TOKEN }}
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Archive
        uses: MirrorChyan/uploading-action@v1
        with:
          filetype: local
          mirrorchyan_rid: ArkModelsRepo
          filename: mirrorchyan.zip
          version_name: ${{ steps.version_name.outputs.version }}
          upload_token: ${{ secrets.MIRROR_CHYAN_TOKEN }}
